# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :CD do |values|

 def increment_version_code(gradle_build: '/Users/akshay-goqii/Documents/Dev/AndroidProject/gitProject/app/build.gradle')
    sh %Q{cd ../ && echo "$(awk '{sub(/versionCode [[:digit:]]+$/,"versionCode "$2+1)}1' #{gradle_build})" > #{gradle_build} && cd -}
 


deploygate(
  api_token: '617d2893a897d843836c93c760cfd3c27cd0c6fc',
  user: 'Indrapatel',
  apk: "app/build/outputs/apk/debug/app-debug.apk",
  message: 'Akshay Android Continues integration Build',
)

  end
end
